PROJECT/backend/models/TblTMutasiAset.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "tbl_t_mutasi_aset".
 *
 * @property string $mutasi_id
 * @property integer $pencatatan_id
 * @property string $kode_trans
 * @property string $tanggal_trans
 * @property string $lokasi
 * @property string $lokasi_tujuan
 * @property integer $jumlah
 * @property string $alasan_mutasi
 * @property string $status_mutasi
 * @property string $status_pindah
 * @property string $created_date
 * @property integer $created_by
 * @property string $created_ip
 * @property string $modified_date
 * @property integer $modified_by
 * @property string $modified_ip
 * @property integer $barang_id
 *
 * @property TblTPencatatanAset $pencatatan
 * @property User $createdBy
 */
class TblTMutasiAset extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_t_mutasi_aset';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pencatatan_id', 'kode_trans', 'tanggal_trans', 'lokasi', 'lokasi_tujuan', 'jumlah', 'alasan_mutasi', 'created_date', 'created_by'], 'required'],
            [['pencatatan_id', 'jumlah', 'created_by', 'modified_by', 'barang_id'], 'integer'],
            [['tanggal_trans', 'created_date', 'modified_date'], 'safe'],
            [['kode_trans'], 'string', 'max' => 30],
            [['lokasi', 'lokasi_tujuan', 'alasan_mutasi', 'status_mutasi', 'status_pindah'], 'string', 'max' => 255],
            [['created_ip', 'modified_ip'], 'string', 'max' => 15],
            [['pencatatan_id'], 'exist', 'skipOnError' => true, 'targetClass' => TblTPencatatanAset::className(), 'targetAttribute' => ['pencatatan_id' => 'pencatatan_id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'mutasi_id' => 'Mutasi ID',
            'pencatatan_id' => 'Pencatatan Aset',
            'kode_trans' => 'Kode Mutasi',
            'tanggal_trans' => 'Tanggal Mutasi',
            'lokasi' => 'Lokasi Awal',
            'lokasi_tujuan' => 'Lokasi Tujuan',
            'jumlah' => 'Jumlah',
            'alasan_mutasi' => 'Alasan Mutasi',
            'status_mutasi' => 'Status Mutasi',
            'status_pindah' => 'Status Pindah',
            'created_date' => 'Created Date',
            'created_by' => 'Created By',
            'created_ip' => 'Created Ip',
            'modified_date' => 'Modified Date',
            'modified_by' => 'Modified By',
            'modified_ip' => 'Modified Ip',
            'barang_id' => 'Barang ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPencatatan()
    {
        return $this->hasOne(TblTPencatatanAset::className(), ['pencatatan_id' => 'pencatatan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    public function getGedung3()
    {
        return $this->hasOne(TblRGedung::className(), ['gedung_id' => 'lokasi']);
    }

    public function getGedung2()
    {
        return $this->hasOne(TblRGedung::className(), ['gedung_id' => 'lokasi_tujuan']);
    }
}

PROJECT/frontend/models/TblTMutasiAset.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "tbl_t_mutasi_aset".
 *
 * @property string $mutasi_id
 * @property integer $buku_id
 * @property string $kode_trans
 * @property string $tanggal_trans
 * @property integer $lokasi
 * @property integer $baik
 * @property integer $rusak
 * @property string $alasan_mutasi
 * @property string $created_date
 * @property integer $created_by
 * @property string $created_ip
 * @property string $modified_date
 * @property integer $modified_by
 * @property string $modified_ip
 *
 * @property TblTBukuinventory $buku
 */
class TblTMutasiAset extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_t_mutasi_aset';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['buku_id', 'kode_trans'], 'required'],
            [['buku_id', 'lokasi', 'baik', 'rusak', 'created_by', 'modified_by'], 'integer'],
            [['tanggal_trans', 'created_date', 'modified_date'], 'safe'],
            [['kode_trans'], 'string', 'max' => 30],
            [['alasan_mutasi'], 'string', 'max' => 255],
            [['created_ip', 'modified_ip'], 'string', 'max' => 15],
            [['buku_id'], 'exist', 'skipOnError' => true, 'targetClass' => TblTBukuinventory::className(), 'targetAttribute' => ['buku_id' => 'buku_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'mutasi_id' => 'ID',
            'buku_id' => 'Buku ID',
            'kode_trans' => 'Kode Transaksi',
            'tanggal_trans' => 'Tanggal Transaksi',
            'lokasi' => 'Lokasi',
            'baik' => 'Baik',
            'rusak' => 'Rusak',
            'alasan_mutasi' => 'Alasan Mutasi',
            'created_date' => 'Created Date',
            'created_by' => 'Created By',
            'created_ip' => 'Created Ip',
            'modified_date' => 'Modified Date',
            'modified_by' => 'Modified By',
            'modified_ip' => 'Modified Ip',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuku()
    {
        return $this->hasOne(TblTBukuinventory::className(), ['buku_id' => 'buku_id']);
    }
}

PROJECT/backend/controllers/TblTMutasiAsetController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\TblTMutasiAset;
use backend\models\TblTMutasiAsetSearch;
use backend\models\TblRGedung;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\models\TblTPencatatanAset;
use kartik\mpdf\Pdf;
/**
 * TblTMutasiAsetController implements the CRUD actions for TblTMutasiAset model.
 */
class TblTMutasiAsetController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all TblTMutasiAset models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TblTMutasiAsetSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TblTMutasiAset model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
 

    public function actionGetPdf($id) {
        
    

        $pdf = new Pdf([
            'filename' => 'bukti_mutasi.pdf',
            'mode' => Pdf::MODE_UTF8,
                'content' => $this->renderPartial('view2', [
            'model' => $this->findModel($id)]),
                'options' => [
                'title' => 'Cetak Bukti Mutasi - PDF' ,
                'subject' => 'Cetak Bukti Mutasi'
            ],
            'methods' => [
                'SetHeader' => ['Cetak Bukti'],
                'SetFooter' => ['|Page {PAGENO}|'],
            ]
        ]);
        return $pdf->render();
    }



 public function actionViewRiwayatMutasiBarang($barang_id)
    {
        $searchModel = new TblTMutasiAsetSearch(['barang_id'=>$barang_id]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('view_riwayat_mutasi_barang', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new TblTMutasiAset model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */


    public function actionCreate()
    {
        $model = new TblTMutasiAset();
        $model->created_by = Yii::$app->user->id;
        $model->created_date = date('Y-m-d');
        $model->created_ip = Yii::$app->getRequest()->getUserIP();
        // $model->deleted = '0';
        if ($model->load(Yii::$app->request->post())) {
            $model_tmp = TblRGedung::find()->where(["nama"=>$model->lokasi])->one();
            $model->lokasi = $model_tmp->gedung_id; 
            $model->save();
            $jumlahmutasi = $model->jumlah;
            // $jumlahmutasi = (new \yii\db\Query())
            //     ->select ('jumlah')
            //     ->from('tbl_t_mutasi_aset')
            //     ->where(['mutasi_id' => $model->mutasi_id])
            //     ->scalar();


            $jumlahpencatatan = (new \yii\db\Query())
                ->select ('jumlah')
                ->from('tbl_t_pencatatan_aset')
                ->where(['pencatatan_id' => $model->pencatatan_id])
                ->scalar();


            $gedungpencatatan = (new \yii\db\Query())
                ->select ('gedung_id')
                ->from('tbl_t_pencatatan_aset')
                ->where(['pencatatan_id' => $model->pencatatan_id])
                ->scalar();
// var_dump($gedungpencatatan);die();
                $gedungmutasi = $model->lokasi_tujuan;
            // $gedungmutasi = (new \yii\db\Query())
            //     ->select ('lokasi_tujuan')
            //     ->from('tbl_t_mutasi_aset')
            //     ->where(['mutasi_id' => $model->mutasi_id])
            //     ->scalar();

            $TransDate = (new \yii\db\Query())
                ->select ('tanggal_trans')
                ->from('tbl_t_pencatatan_aset')
                ->where(['pencatatan_id' => $model->pencatatan_id])
                ->scalar();


            // var_dump($gedungmutasi);die();
            // var_dump($gedungpencatatan);die();

            $jumlahAkhir = $jumlahpencatatan-$jumlahmutasi;

            // echo $model->jumlah;
            // echo '\n';
            // echo $jumlahpencatatan;
            // echo '\n';
            // echo $gedungpencatatan;
            // echo '\n';
           //  echo $TransDate;
          //   echo "\n";
            // echo  $model->tanggal_trans;
            if( ($jumlahmutasi <= $jumlahpencatatan) && ($gedungpencatatan!=$gedungmutasi)  ){

                Yii::$app->session->setFlash('success', "Proses Mutasi Barang berhasil dilakukan");

                Yii::$app->db->createCommand("Update tbl_t_pencatatan_aset set jumlah = $jumlahAkhir where pencatatan_id = $model->pencatatan_id")->execute();


                Yii::$app->db->createCommand("Update tbl_t_mutasi_aset set status_mutasi = '1'where pencatatan_id = $model->pencatatan_id")->execute();

                Yii::$app->db->createCommand("Update tbl_t_mutasi_aset set status_pindah = '1' where pencatatan_id = $model->pencatatan_id")->execute();

            }

            else{

                Yii::$app->session->setFlash('error', "Jumlah barang yang Anda input salah!");

                Yii::$app->db->createCommand("Update tbl_t_mutasi_aset set status_mutasi = '2' where pencatatan_id = $model->pencatatan_id")->execute();

            }




           return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }


    /**
     * Updates an existing TblTMutasiAset model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->mutasi_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing TblTMutasiAset model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }




    public function actionPindah($id)
    {
        // var_dump($id);die();

        Yii::$app->db->createCommand("Update tbl_t_mutasi_aset set status_pindah = '2' where mutasi_id = $id")->execute();


        $this->findModel($id);
        return $this->redirect(['view']);
    }



// public function actionPindah($id){
//     $searchModel = new TblTMutasiAsetSear();
//         $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
//         $user = Yii::$app->user->id;
//         $model = $this->findModel($id);

//         Yii::$app->db->createCommand("Update tbl_t_mutasi_aset set status_pindah = 2 where mutasi_id = $id")->execute();

//         $model->save();
// return $this->render('view', [
//                 'searchModel' => $searchModel,
//                 'dataProvider' => $dataProvider,
//             ]);
// }


    /**
     * Finds the TblTMutasiAset model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return TblTMutasiAset the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TblTMutasiAset::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

PROJECT/frontend/controllers/TblTMutasiAsetController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\TblTMutasiAset;
use frontend\models\TblTMutasiAsetSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TblTMutasiAsetController implements the CRUD actions for TblTMutasiAset model.
 */
class TblTMutasiAsetController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all TblTMutasiAset models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TblTMutasiAsetSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TblTMutasiAset model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TblTMutasiAset model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TblTMutasiAset();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->mutasi_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing TblTMutasiAset model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->mutasi_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing TblTMutasiAset model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TblTMutasiAset model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return TblTMutasiAset the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TblTMutasiAset::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

PROJECT/backend/views/tbl-t-mutasi-aset/_menu.php
<?php

/*
 * This file is part of the Dektrium project
 *
 * (c) Dektrium project <http://github.com/dektrium>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

use yii\bootstrap\Nav;

?>

<?= Nav::widget([
    'options' => [
        'class' => 'nav-tabs',
        'style' => 'margin-bottom: 15px',
    ],
    'items' => [
        [
            'label'   => Yii::t('app', 'Buku Inventory'),
            'url'     => ['/tbl-t-buku-inventory/index'],
        ],

        [
            'label'   => Yii::t('app', 'Pencatatan Aset'),
            'url'     => ['/tbl-t-pencatatan-aset/index'],
        ],

        // [
        //     'label'   => Yii::t('app', 'Pelepasan Aset'),
        //     'url'     => ['/tbl-t-pelepasan-aset/index'],
        // ],
        [
            'label' => Yii::t('app','Mutasi Aset'),
            'url'     => ['/tbl-t-mutasi-aset/index'],
        ],
        [
            'label' => Yii::t('app','Kerusakan'),
            'url'     => ['/tbl-r-kerusakan/index'],
        ],
    ],
]) ?>

PROJECT/backend/views/tbl-t-mutasi-aset/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use yii\helpers\ArrayHelper;
use backend\models\TblRStatus;
use yii\widgets\Pjax;
use backend\models\TblRGedung;
use kartik\select2\Select2;
// use yii\helpers\ArrayHelper;


/* @var $this yii\web\View */
/* @var $model backend\models\TblTMutasiAsetSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tbl-tmutasi-aset-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

   <?= $form->field($model, 'tanggal_trans')->widget(
        DatePicker::classname(), [
            'name' => 'dp_3',
            'type' => DatePicker::TYPE_COMPONENT_APPEND,
            'value' => '23-Februari-1998',
            'pluginOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-mm-dd'
            ],
        ]); ?>


<?= $form->field($model, 'lokasi')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(TblRGedung::find()->all(),'gedung_id', 'nama'),
        'language' => 'en',
        'options' => ['placeholder' => '- Pilih Barang -', 'id'=>'pencatatanId'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]);?>


    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

PROJECT/backend/views/tbl-t-mutasi-aset/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\TblTMutasiAsetSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Mutasi Aset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tbl-tmutasi-aset-index">

    <h1><?= Html::encode($this->title) ?></h1>


<?= $this->render('/tbl-t-mutasi-aset/_menu') ?>
    
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Daftarkan Mutasi Aset Baru', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'mutasi_id',
            // 'pencatatan_id',
            'kode_trans',
            'tanggal_trans',



            [
                'label' => 'Lokasi Awal',
                'format' => 'raw',
                'value' => function($model){
                    return $model->gedung3->nama;
                },
            ],

            [
                'label' => 'Lokasi Tujuan',
                'format' => 'raw',
                'value' => function($model){
                    return $model->gedung2->nama;
                },
            ],



            'jumlah',
            [
                'attribute' => 'Status Mutasi',
                'format' => 'raw',
                'value' => function($model){
                    if($model->status_mutasi == 1)
                        return "Berhasil";
                    else
                        return "Tidak Berhasil";
                }
            ],
            [
                'attribute' => 'Status Pindah',
                'format' => 'raw',
                'value' => function($model){
                    if($model->status_pindah != 1)
                        return "Sudah dipindahkan";
                    else
                        return "Belum Dipindahkan";
                }
            ],


            [ 'attribute' => 'Keterangan',
                'format' => 'raw',
                'value' => function ($model){
                    return '<div>'.'<center>'.Html::a('Detail', ['tbl-t-mutasi-aset/view','id'=>$model->mutasi_id],['class'=>'  btn btn-success']).'</center>'.'</div>';
                },
            ],
            // 'alasan_mutasi',
            // 'created_date',
            // 'created_by',
            // 'created_ip',
            // 'modified_date',
            // 'modified_by',
            // 'modified_ip',

            
        ],
    ]); ?>
</div>

PROJECT/backend/views/tbl-t-mutasi-aset/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use backend\models\TblTMutasiAset;
use backend\models\TblTPencatatanAset;
use backend\models\TblRBarang;
use backend\models\TblRGedung;

$mei = new TblRBarang();


$PencatatanId = (new \yii\db\Query())
    ->select ('pencatatan_id')
    ->from('tbl_t_mutasi_aset')
    ->where(['mutasi_id' => $model->mutasi_id])
    ->scalar();

$StatusMutasi = (new \yii\db\Query())
    ->select ('status_mutasi')
    ->from('tbl_t_mutasi_aset')
    ->where(['mutasi_id' => $model->mutasi_id])
    ->scalar();

$BarangId = (new \yii\db\Query())
    ->select ('barang_id')
    ->from('tbl_t_pencatatan_aset')
    ->where(['pencatatan_id' => $PencatatanId])
    ->scalar();

$BarangName = (new \yii\db\Query())
    ->select ('nama')
    ->from('tbl_r_barang')
    ->where(['barang_id' => $BarangId])
    ->scalar();


// $gedungs = TblRGedung::find()->where(['gedung_id' => $gedungs->])

// var_dump($BarangName);die();
/* @var $this yii\web\View */
/* @var $model backend\models\TblTMutasiAset */

$this->title =$BarangName;
$this->params['breadcrumbs'][] = ['label' => 'Tbl Tmutasi Asets', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tbl-tmutasi-aset-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->mutasi_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->mutasi_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>

    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            // 'mutasi_id',

            // [
            //     'attribute' => 'Id Pencatatan',
            //     'value' => $model->pencatatan->pencatatan_id,
            // ],

            [
                'attribute' => 'Barang',
                'value' => $model->pencatatan->keterangan,
            ],

            'kode_trans',

            'tanggal_trans',

             [
                'attribute' => 'Lokasi Awal',
                'value' => $model->gedung3->nama,
            ],


            // 'lokasi_tujuan',  
            [
                'attribute' => 'Lokasi Tujuan',
                'value' => $model->gedung2->nama,
            ],

            'jumlah',

            'alasan_mutasi',

             [
                'attribute' => 'Status Mutasi',
                'format' => 'raw',
                'value' => function($model){
                    if($model->status_mutasi == 1)
                        return "Berhasil";
                    else
                        return "Tidak Berhasil";
                }
            ],
            [
                'attribute' => 'Status Pindah',
                'format' => 'raw',
                'value' => function($model){
                    if($model->status_pindah != 1)
                        return "Sudah dipindahkan";
                    else
                        return "Belum Dipindahkan";
                }
            ],

            'created_date',
            [
                'attribute' => 'Created By',
                'value' => $model->createdBy->nama,
            ],

            [
                'attribute' => 'Action',
                'format' => 'raw',
                'value' => function($model){

                    $StatusMutasi = (new \yii\db\Query())
                        ->select ('status_mutasi')
                        ->from('tbl_t_mutasi_aset')
                        ->where(['mutasi_id' => $model->mutasi_id])
                        ->scalar();


// var_dump($model->mutasi_id);die();
                    // $detail = TblTPeminjamanDetail::find()->where(['peminjaman_id'=>$model->peminjaman_id])->one();;

                    if($StatusMutasi != 2){ 

                        return '<div><left>' . Html::a('Cetak Bukti Mutasi', ['tbl-t-mutasi-aset/get-pdf','id'=>$model->mutasi_id], ['class' => 'btn btn-success', 'data' => [
                                'confirm' => 'Kamu yakin barang sudah ditangan peminjam?',
                                'method' => 'post',],
                            ]).'&nbsp;

                    ' . Html::a('Update Status Pindah', ['tbl-t-mutasi-aset/pindah', 'id' => $model->mutasi_id], ['class' => 'btn btn-success', 'data' => ['confirm' => 'Kamu yakin barang sudah dipindahkan?',
                                'method' => 'post',]  ]).
                            '</center></div>';
                    }
                    else
                    {
                        return '-';
                    }
                }
            ],
        ],
    ])

    ?>

</div>