PROJECT/backend/models/TblTPermintaan.php
<?php

namespace backend\models;

use Yii;
use backend\models\User;
/**
 * This is the model class for table "tbl_t_permintaan".
 *
 * @property string $permintaan_id
 * @property integer $tipe
 * @property integer $pemohon
 * @property string $tanggal_trans
 * @property integer $bulan_trans
 * @property string $tahun_trans
 * @property string $keterangan
 * @property string $created_date
 * @property integer $created_by
 * @property string $created_ip
 * @property string $modified_date
 * @property integer $modified_by
 * @property string $modified_ip
 *
 * @property TblTPermintaanDetail[] $tblTPermintaanDetails
 */
class TblTPermintaan extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_t_permintaan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['no_dokumen', 'pemohon'], 'required'],
            [['pemohon', 'tahun_trans', 'bulan_trans', 'created_by', 'modified_by'], 'integer'],
            [['tanggal_trans', 'tahun_trans', 'created_date', 'modified_date', 'modified_ip'], 'safe'],
            [['keterangan', 'alasan_penolakan'], 'string'],
            [['no_dokumen'], 'string', 'max' => 50],
            [['created_ip'], 'string', 'max' => 15],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'permintaan_id' => 'Permintaan ID',
            'no_dokumen' => 'No Dokumen',
            'tipe' => 'Tipe',
            'pemohon' => 'Pemohon',
            'tanggal_trans' => 'Tanggal Trans',
            'bulan_trans' => 'Bulan Trans',
            'tahun_trans' => 'Tahun Trans',
            'keterangan' => 'Keterangan',
            'alasan_penolakan' => 'Alasan Penolakan',
            'created_date' => 'Created Date',
            'created_by' => 'Created By',
            'created_ip' => 'Created Ip',
            'modified_date' => 'Modified Date',
            'modified_by' => 'Modified By',
            'modified_ip' => 'Modified Ip',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTblTPermintaanDetails()
    {
        return $this->hasMany(TblTPermintaanDetail::className(), ['permintaan_id' => 'permintaan_id']);
    }
    
    public function getPemohon()
    {
        $pemohon = User::find()->where(['id'=>$model->pemohon])->one();
        return $pemohon->nama;
    }
}

PROJECT/frontend/models/TblTPermintaan.php
<?php

namespace frontend\models;

use Yii;
use frontend\models\User;
/**
 * This is the model class for table "tbl_t_permintaan".
 *
 * @property string $permintaan_id
 * @property integer $tipe
 * @property integer $pemohon
 * @property string $tanggal_trans
 * @property integer $bulan_trans
 * @property string $tahun_trans
 * @property string $keterangan
 * @property string $created_date
 * @property integer $created_by
 * @property string $created_ip
 * @property string $modified_date
 * @property integer $modified_by
 * @property string $modified_ip
 *
 * @property TblTPermintaanDetail[] $tblTPermintaanDetails
 */
class TblTPermintaan extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_t_permintaan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['no_dokumen', 'pemohon', 'tahun_trans', 'bulan_trans', 'no_dokumen'], 'required'],
            [['pemohon', 'tahun_trans', 'bulan_trans', 'created_by', 'modified_by'], 'integer'],
            [['tanggal_trans', 'tahun_trans', 'created_date', 'modified_date', 'modified_ip'], 'safe'],
            [['keterangan'], 'string'],
            [['no_dokumen'], 'string', 'max' => 50],
            [['created_ip'], 'string', 'max' => 15]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'permintaan_id' => 'Permintaan ID',
            'no_dokumen' => 'Nomor Dokumen',
            'tipe' => 'Tipe',
            'pemohon' => 'Pemohon',
            'tanggal_trans' => 'Tanggal Transaksi',
            'bulan_trans' => 'Bulan Trans',
            'tahun_trans' => 'Tahun Trans',
            'keterangan' => 'Keterangan',
            'created_date' => 'Created Date',
            'created_by' => 'Created By',
            'created_ip' => 'Created Ip',
            'modified_date' => 'Modified Date',
            'modified_by' => 'Modified By',
            'modified_ip' => 'Modified Ip',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTblTPermintaanDetails()
    {
        return $this->hasMany(TblTPermintaanDetail::className(), ['permintaan_id' => 'permintaan_id']);
    }
    
    public function getPemohon()
    {
        $pemohon = User::find()->where(['id'=>$model->pemohon])->one();
        return $pemohon->nama;
    }
}

PROJECT/backend/controllers/TblTPermintaanController.php
<?php

namespace backend\controllers;

use Yii;
use yii\data\SqlDataProvider;
use backend\models\TblTPermintaan;
use backend\models\TblTPermintaanDetail;
use backend\models\TblTPermintaanSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\models\TblRBarang;
use backend\models\Model;
use backend\models\TblTStokbarang;
use kartik\mpdf\Pdf;

/**
 * TblTPermintaanController implements the CRUD actions for TblTPermintaan model.
 */
class TblTPermintaanController extends Controller
{
    public $dokumen = 274;
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all TblTPermintaan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TblTPermintaanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TblTPermintaan model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
//        $searchModel = new TblTPermintaanSearch();
//        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
//        
//        return $this->render('view', [
//            'model' => $this->findModel($id),
//            'dataProvider' => $dataProvider,
//        ]);
        $model = TblTPermintaan::find()->where(['permintaan_id'=>$id]);
        $dataProviderPermintaan = new \yii\data\ActiveDataProvider(
                [
                    'query'=>$model,
                ]
                );
        
        $models1TblPermintaanDetail = TblTPermintaanDetail::find()->where(['permintaan_id'=>$id]);
        
        $dataProviderPermintaanDetail = new \yii\data\ActiveDataProvider([
            'query'=>$models1TblPermintaanDetail,
        ]);
        
        return $this->render('view', [
                    'model' => $this->findModel($id),
                    'dataProviderPermintaanDetail'=>$dataProviderPermintaanDetail,
        ]);
    }

    public function actionCreate()
    {
        $model = new TblTPermintaan();
        $modelsDetail = [new TblTPermintaanDetail()];
        
        if ($model->load(Yii::$app->request->post())){
            if(!($model->tanggal_trans < date('Y-m-d')))
            {
                $modelsDetail = Model::createMultiple(TblTPermintaanDetail::classname());
                Model::loadMultiple($modelsDetail, Yii::$app->request->post());

                $model->pemohon = Yii::$app->user->id;
                $model->tipe = 1;
                $model->created_by = Yii::$app->user->id;
                $model->created_date = date('Y-m-d');
                $model->created_ip = Yii::$app->getRequest()->getUserIP();
                // validate all models  
                $valid = $model->validate();
                $valid = Model::validateMultiple($modelsDetail);

                if (!$valid) {
                    $transaction = \Yii::$app->db->beginTransaction();
                    try {
                        if ($flag = $model->save(false)) {
                            foreach ($modelsDetail as $modelDetail) {
                                $modelDetail->permintaan_id = $model->permintaan_id;
                                $modelDetail->created_by = Yii::$app->user->id;
                                $modelDetail->created_date = date('Y-m-d');
                                $modelDetail->created_ip = Yii::$app->getRequest()->getUserIP();
                                $modelDetail->status = Yii::$app->db->createCommand("SELECT tbl_r_status.no FROM tbl_r_status WHERE kode = 'status_permintaan' AND nama = 'Requested'")->queryScalar();
                                if (! ($flag = $modelDetail->save(false))) {
                                    $transaction->rollBack();
                                    break;
                                }
                            }
                        }
                        if ($flag) {
                            $transaction->commit();
                            return $this->redirect(['index']);
                        }
                    } catch (Exception $e) {
                        $transaction->rollBack();
                    }
                }
            }
            else
            {
                Yii::$app->getSession()->setFlash(
                    'error','Request Gagal ! Periksa tanggal request Anda!'
                );
                return $this->render('create', [
                    'model' => $model,
                    'modelsDetail' => (empty($modelsDetail)) ? [new TbtTPermintaanDetail] : $modelsDetail
                ]);
            }
        }
        
        return $this->render('create', [
            'model' => $model,
            'modelsDetail' => (empty($modelsDetail)) ? [new TbtTPermintaanDetail] : $modelsDetail
        ]);
        
    }
    /**
     * Updates an existing TblTPermintaan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        //$detail = new TblTPermintaanDetail();
        //$barang = new TblRBarang();
        $model = $this->findModel($id);
        //$model1 = $detail->findModel($id);        
        if ($model->load(Yii::$app->request->post())) {
            
            $model->modified_by = Yii::$app->user->id;
            $model->modified_date = date('Y-m-d');
            $model->modified_ip = Yii::$app->getRequest()->getUserIP();
            $model->save();
            Yii::$app->db->createCommand("Update tbl_t_permintaan set modified_date= '$model->modified_date', modified_by = $model->modified_by, modified_ip = '$model->modified_ip', alasan_penolakan = '$model->alasan_penolakan' where permintaan_id = $id")->execute();
            
           
            //RejectRequest($id);
            $searchModel = new TblTPermintaanSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            $user = Yii::$app->user->id; 
            //$model = $this->findModel($id);
            $detail = TblTPermintaanDetail::find()->where(['permintaan_id'=>$model->permintaan_id])->one();
            Yii::$app->db->createCommand("Update tbl_t_permintaan_detail set status = 3, status_by = $user where permintaan_id = $id AND status = 1")->execute();

           //$detail->status = Yii::$app->db->createCommand("SELECT tbl_r_status.no FROM tbl_r_status WHERE kode = 'status_permintaan' AND nama = 'Rejected'")->queryScalar();
            //$detail->status_by = Yii::$app->user->id;
            $detail->save();

            $date = date('H:i');
            echo $date;
            $sapa = '';
            if ($date < 12)
                $sapa = "Pagi";
            else if ($date < 14)
                $sapa = 'Siang';
            else if ($date < 18)
                $sapa = 'Sore';

            $message = 'Pemberitahuan Request Ditolak<br>'
                    . 'Selamat ' . $sapa . ' <br>'
                    .' Kami ingin pihak Staff Inventory memberitahukan bahwa Request yang dilakukan oleh Bapak/Ibu Telah kami tolak.'
                    .'Dikarenakan oleh '. $model->alasan_penolakan . ' <br> <br>Atas perhatian Bapak/Ibu Sekalian, Kami Ucapkan Terimakasih'
                    . '<br><br><br> <hr> Dikirim oleh : <br>'
                    . '<b>Sistem Informasi Inventory ( SII ) : by Staff Inventory <b>';

            $pemohon = \backend\models\User::findOne(['id'=>$model->pemohon]); 

            $tujuan = $pemohon->email;

            $email = Yii::$app->mailer->compose()
                    ->setFrom([\Yii::$app->params['supportEmail'] => 'Sistem Informasi Inventory'])
                    ->setTo($tujuan)
                    ->setSubject("Notifikasi Request Ditolak")
                    ->setHtmlBody($message)
                    ->send();

            $connection = \Yii::$app->db;
            
            return $this->render('index', [
                'model' => $model,
                'detail' => $detail,
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing TblTPermintaan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $searchModel = new TblTPermintaanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $model = $this->findModel($id);
        $detail = TblTPermintaanDetail::find()->where(['permintaan_id'=>$model->permintaan_id])->one();
        Yii::$app->db->createCommand("delete from tbl_t_permintaan_detail  where permintaan_id = $id")->execute();
        Yii::$app->db->createCommand("delete from tbl_t_permintaan where permintaan_id = $id")->execute();
        $detail->save();
        
        return $this->render('index', [
                'model' => $model,
                'detail' => $detail,
                'dataProvider' => $dataProvider,
            ]);
    }
    public function setDokumen()
    {
        $this->dokumen++;
    }







    public function actionApprove($id)
    {
        $searchModel = new TblTPermintaanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $user = Yii::$app->user->id; 
        $model = $this->findModel($id);

PROJECT/frontend/views/tbl-t-permintaan/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\models\TblTPermintaanDetail;
use yii\helpers\ArrayHelper;
use frontend\models\TblRBarang;
use frontend\models\TblRStatus;
use kartik\date\DatePicker;
use wbraganca\dynamicform\DynamicFormWidget;

/* @var $this yii\web\View */
/* @var $model frontend\models\TblTPermintaan */
/* @var $form yii\widgets\ActiveForm */
$modelsDetail = [new TblTPermintaanDetail()];
$barang = new TblRBarang();
?>

<div class="tbl-tpermintaan-form">

    <?php $form = ActiveForm::begin(['id' => 'dynamic-form']); ?>

    <?= $form->field($model, 'tanggal_trans')->widget(
        DatePicker::classname(), [
            'name' => 'dp_3',
            'type' => DatePicker::TYPE_COMPONENT_APPEND,
            'value' => '23-Februari-1998',
            'pluginOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-mm-dd',
            ],
        ]); ?>



    <?= $form->field($model, 'keterangan')->textarea(['rows' => 6]) ?>
    
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading"><h4><i class="glyphicon glyphicon-envelope"></i> Tambahkan Detail Permintaan</h4></div>
            <div class="panel-body">
                <?php
                DynamicFormWidget::begin([
                    'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
                    'widgetBody' => '.container-items', // required: css class selector
                    'widgetItem' => '.item', // required: css class
                    'limit' => 999, // the maximum times, an element can be cloned (default 999)
                    'min' => 1, // 0 or 1 (default 1)
                    'insertButton' => '.add-item', // css class
                    'deleteButton' => '.remove-item', // css class
                    'model' => $modelsDetail[0],
                    'formId' => 'dynamic-form',
                    'formFields' => [
                        'barang_id',
                        'jumlah',
                        'satuan',
                        'keterangan',
                    ],
                ]);
                ?>

                <div class="container-items"><!-- widgetContainer -->
                    <?php foreach ($modelsDetail as $i => $modelsDetail): ?>
                        <div class="item panel panel-default"><!-- widgetBody -->
                            <div class="panel-heading">
                                <h3 class="panel-title pull-left">Detail Permintaan</h3>
                                <div class="pull-right">
                                    <button type="button" class="add-item btn btn-success btn-xs"><i class="glyphicon glyphicon-plus"></i></button>
                                    <button type="button" class="remove-item btn btn-danger btn-xs"><i class="glyphicon glyphicon-minus"></i></button>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="panel-body">
                                <?php
                                // necessary for update action.
                                if (!$modelsDetail->isNewRecord) {
                                    echo Html::activeHiddenInput($modelsDetail, "[{$i}]id");
                                }

                                ?>

                                <div class="row">
                                    <div class="col-sm-6">
                                        <?= $form->field($modelsDetail, "[{$i}]barang_id")->dropDownList(ArrayHelper::map(TblRBarang::find()->rightJoin('tbl_t_stokbarang', 'tbl_t_stokbarang.barang_id = tbl_r_barang.barang_id')->where("(tbl_r_barang.kategori = '1')")->andWhere("(tbl_t_stokbarang.deleted = '0')")->all(), 'barang_id', 'nama'), ['prompt' => '-Pilih Barang']) ?>
                                    </div>

                                    <div class="col-sm-6">
                                        <?= $form->field($modelsDetail, "[{$i}]jumlah")->dropDownList(range(1, 100)) ?>
                                    </div>  
                                    
                                 
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
            <?php DynamicFormWidget::end(); ?>
                </div>
            </div>
        </div>
    </div>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Kirim' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

PROJECT/frontend/views/tbl-t-permintaan/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use yii\helpers\ArrayHelper;
use frontend\models\TblRStatus;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model frontend\models\TblTPermintaanSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tbl-tpermintaan-search" style="width:300px">
    <?php Pjax::begin(); ?>
    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <!--?= $form->field($model, 'pemohon')->dropDownList(ArrayHelper::map(TblRStatus::find()->where("(kode = 'divisi')")->all(),'no', 'nama'),['prompt'=>'-Pilih divisi-', 'style'=>'width:300px'])?-->

    <?= $form->field($model, 'tanggal_trans')->widget(
        DatePicker::classname(), [
            'name' => 'dp_3',
            'type' => DatePicker::TYPE_COMPONENT_APPEND,
            'value' => '23-Februari-1998',
            'pluginOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-mm-dd'
            ],
        ]); ?>

    <!--?= $form->field($model, 'bulan_trans')->dropDownList(ArrayHelper::map(TblRStatus::find()->where("(kode = 'bulan')")->all(),'no', 'nama'),['prompt'=>'-Pilih Bulan-', 'style'=>'width:300px'])?-->

    <?php // echo $form->field($model, 'tahun_trans') ?>

    <?php // echo $form->field($model, 'keterangan') ?>

    <?php // echo $form->field($model, 'created_date') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'created_ip') ?>

    <?php // echo $form->field($model, 'modified_date') ?>

    <?php // echo $form->field($model, 'modified_by') ?>

    <?php // echo $form->field($model, 'modified_ip') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Reset', ['index'], ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    <?php Pjax::end(); ?>
</div>

PROJECT/frontend/views/tbl-t-permintaan/create.php
<?php

use yii\helpers\Html;
use frontend\models\TblTPermintaanDetail;


/* @var $this yii\web\View */
/* @var $model frontend\models\TblTPermintaan */

// $this->title = 'Form Permintaan Barang Habis';
$this->params['breadcrumbs'][] = ['label' => 'Permintaan', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tbl-tpermintaan-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'modelsDetail' => (empty($modelsDetail)) ? [new TbtTPermintaanDetail] : $modelsDetail
    ]) ?>

</div>

PROJECT/frontend/views/tbl-t-permintaan/index.php
<?php
$server="localhost";
$username="root";
$password="";
$database="inventory"; 
$mei = mysqli_connect($server,$username,$password)or die('tidak terkoneksi dengan db');
// mysql_select_db($database)or die('tidak terkoneksi dengan db');
use yii\helpers\Html;
use yii\grid\GridView;
use frontend\models\TblTPermintaanDetail;
use frontend\models\TblRBarang;
use frontend\models\User;
use frontend\models\TblRStatus;
use yii\bootstrap\Modal;
use yii\helpers\Url;
use yii\models\TblTStokBarang;


/* @var $this yii\web\View */
/* @var $searchModel frontend\models\TblTPermintaanSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$detail = new TblTPermintaanDetail();
$this->title = 'Permintaan';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="tbl-tpermintaan-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>


 <?= Html::button('Buat Permintaan Baru ', ['value'=>Url::to('index.php?r=tbl-t-permintaan/create'),'class' => 'btn btn-success', 'id'=>'modalButton']) ?>

    <?php
        Modal::begin([
                'header'=>'<h4>Form Permintaan Barang Habis</h4>',
                'id' => 'modal',
                'size' => 'modal-lg',
       ]);

        echo "<div id = 'modalContent'> </div>";
        Modal::end();

    ?>
<p>
 <?= Html::a('Lihat Daftar Barang Habis', ['tbl-t-stokbarang/index'], ['class' => 'btn btn-success'])  ?>   
</p>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'Pemohon',
                'format' => 'raw',
                'value' => function ($model) {
                    $pemohon = User::find()->where(['id'=>$model->pemohon])->one();
                    return $pemohon->nama;
                },
            ],
            [
                'attribute' => 'Divisi',
                'format' => 'raw',
                'value' => function ($model) {
                    $pemohon = User::find()->where(['id'=>$model->pemohon])->one();
                    $divisi = TblRStatus::find()->where(['kode'=>'divisi', 'no'=>$pemohon->divisi])->one();
                    return $divisi->nama;
                },
            ],
            'tanggal_trans',
            'keterangan:ntext',
                        
            [
                'attribute' => 'Status',
                'format' => 'raw',
                'value' => function ($model) {
                    $detail = TblTPermintaanDetail::find()->where(['permintaan_id'=>$model->permintaan_id])->one();
                    $status = TblRStatus::find()->where(['kode' => 'status_permintaan'])->andWhere(['no' => $detail['status']])->one();
                    return $status['nama'];
                },
            ],
 [ 'attribute' => 'Keterangan',
                'format' => 'raw',
                'value' => function ($model){
                date_default_timezone_set("Asia/Jakarta");
                $end = $model->tanggal_trans;
                $current_date = date("Y-m-d");

                if($current_date > $end){                
                      return '<div>'.'<center>'.Html::a('Peminjaman Kadaluarsa', ['tbl-t-permintaan/view','id'=>$model->permintaan_id],['class'=>' btn btn-danger']).'</center>'.'</div>'
                    ;
                }

                else{

               return '<div>'.'<center>'.Html::a('Detail Permintaan', ['tbl-t-permintaan/view','id'=>$model->permintaan_id],['class'=>' btn btn-success']).'</center>'.'</div>'
                    ;
            }
        },

            ],
            
        ],
    ]); ?>

</div>

PROJECT/frontend/views/tbl-t-permintaan/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\TblTPermintaan */

$this->title = 'Update Permintaan: ' . ' ' . $model->permintaan_id;
$this->params['breadcrumbs'][] = ['label' => 'Tbl Tpermintaans', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->permintaan_id, 'url' => ['view', 'id' => $model->permintaan_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="tbl-tpermintaan-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

PROJECT/frontend/views/tbl-t-permintaan/view2.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;
use backend\models\TblRBarang;
use backend\models\TblRStatus;
use backend\models\TblTPermintaanDetail;
use backend\models\User;
/* @var $this yii\web\View */
/* @var $model backend\models\TblTPermintaan */

$this->title = $model->permintaan_id;
$this->params['breadcrumbs'][] = ['label' => 'Permintaan', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$user = User::findOne(['id'=>$model->pemohon]);
?>

<h1>Permintaan Anda</h1>
<div class="tbl-tpermintaan-view">

<!--    <h1><?= Html::encode($this->title) ?></h1>-->



    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
//            'permintaan_id',
//            'pemohon',
            [
                'label'  => 'Pemohon',
                'value' => $user->nama,
            ],
            'tanggal_trans',
           // 'bulan_trans',
           // 'tahun_trans',
            'keterangan:ntext',
           'created_date',
           // 'created_by',
//            'created_ip',
//            'modified_date',
//            'modified_by',
//            'modified_ip',
        ],
    ]) ?>
    
    <h2 align="center">Detail Permintaan</h2>
    <?= GridView::widget([
        'dataProvider' => $dataProviderPermintaanDetail,
        //'filterModel' => $searchModel,
        'columns' => [
//            ['class' => 'yii\grid\SerialColumn'],

           // 'permintaan_id',
           'barang.nama',
           'satuan',
           'jumlah',
           
//         
            
                        
           
            'created_date',
            'keterangan:ntext',
             [
                'attribute' => 'Status',
                'format' => 'raw',
                'value' => function ($model) {
                    $detail = TblTPermintaanDetail::find()->where(['permintaan_id'=>$model->permintaan_id])->one();
                    $status = TblRStatus::find()->where(['kode' => 'status_permintaan'])->andWhere(['no' => $detail['status']])->one();
                    return $status['nama'];
                },
            ],
        
            
        ],
    ]); ?>



 

</div>